### ISSUE TITLE
PreRelease   Turret Fire transform emissives not displaying correctly 

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#47]
**Pre release**  turrets fire and tracer is default no texture bright pink. this indicates a possible problem with the emissives 
Reproduce; install any weapon fixed or turret and WM  launch and test fire
http://i.imgur.com/M5Rp0hu.png

**Comment by gomker** [comment]
Corrected in  v0.11.1.5

**Comment by stasikos** [comment]
Please, don't hurry closing it. BDArmory.0.11.1.5_11022016.zip still has this issue in clean x64 instal on Linux.

**Comment by kahogeoff** [comment]
Problem still exist on:
* KSP v1.2.0
* BDA v0.11.1.5
* macOS sierra
