### ISSUE TITLE
loading bar freezes on "BDArmory full set/BDArmory/Parts/20mmVulcan/vulcanTurret/bahaGatlingGun"

### ISSUE THREAD

**Issue by Trainman666** [PapaJoesSoup/BDArmory#667]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Support 	    ( Need help getting something to work)

##### KSP and BDA Version
ksp 1.6
```
BDArmory.1.2.4.0_12302018
```

##### OS / ENVIRONMENT
Windows 10

##### SUMMARY

it stops loading

**Comment by Gedas-S** [comment]
See https://github.com/PapaJoesSoup/BDArmory/issues/608

**Comment by Trainman666** [comment]
I know it does not work for me

**Comment by Trainman666** [comment]
I tried that

**Comment by kerbalnaut** [comment]
The same is happening to me

**Comment by kspgamer** [comment]
for me tooo

**Comment by jrodrigv** [comment]
Sorry guys but If you are doing a clean installation using CKAN and you have module manager installed I can confirm that it works without issues

**Comment by ReverseEqua** [comment]
Mine is BDArmory.1.3.3.0_02232020/GameData/BDArmory/Parts/20mmVulcan/vulcanTurret/bahaGatlingGun
and it kinda stop loading.
i downloaded module manager 4.1.3 and physical extender 1.18_02202020. I get all the mods required and it still doesnt load need help

**Comment by kspgamer** [comment]
I have found my solution if you download it it downloads a get bdarmory. 1.3.3_02232020 you need to go into the file you Will find gamedata go into the file and you will see bdarmory ctrl c go back to the gamedata of ksp ctrl v and then there stand bdarmory delete bdarmory_1.3.3_02232020
And done sorry for the bad language in not English its a great mod hope you enjoy

**Comment by kspgamer** [comment]
It took some time to find it but here you go

**Comment by kspgamer** [comment]
The only problem is that almost all extensions are not updated

**Comment by ReverseEqua** [comment]
Thx a lot

**Comment by ReverseEqua** [comment]
It’s fixed now thx

**Comment by A-A-RON438** [comment]
idk what you r talking about? but still have the same problem:(

**Comment by Jbt370** [comment]
ya same but for me its on the 1.3.1 version of KSP

**Comment by Jbt370** [comment]
> The only problem is that almost all extensions are not updated

how do you update them
